### ISSUE TITLE
As a User I want to click on a List element to navigate to a Show view

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#121]
The List component currently provides navigation to a Show view in an id cell, only when the **hasShow** is set to true. This coupled logic to the id cell makes little sense to me.

We could provide navigation support by adding a click event to the whole row when the **hasShow** enables it's usage.

+   [x] Make sure the edit and delete buttons are not wrapped by the row event
+   [x] Refactor List e2e tests to search and click the cell row

**Comment by DanielOrmeno** [comment]
Hello, I've submitted [#170](https://github.com/Cambalab/vue-admin/pull/170) to tackle this.
