### ISSUE TITLE
UI Component Customization

### ISSUE THREAD

**Issue by jejoivanic** [Cambalab/vue-admin#128]
**Is your feature request related to a problem? Please describe.**
This feature has as an objective extend the users' possibilities to customize their application. The UI Component (which is responsible for rendering the drawer, toolbar and current view) is currently used as Vue-Admin defines it, so it would be great if the users could customize the toolbar or the items in the navigation menu and their sorting.

**Describe the solution you'd like**
The UI Component could receive properties that will define the toolbar, navigation menu, etc. individually. If none custom component is passed then the default one will be used.
In order to achieve this, the Custom UI component with its custom inner components should be passed to the Admin component as a property.

**Comment by sgobotta** [comment]
Merged in #131
