### ISSUE TITLE
Add a pre-commit hook to avoid eslint errors/warnings

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#158]
**Is your feature request related to a problem? Please describe.**
#7 enforces developers to write clean code according to prettier eslint rules. It would be nice to have a pre-commit hook that avoids developers committing code with errors or warnings.

**Describe the solution you'd like**
Whenever a developer commits, a pre-commit hook should run the **lint** package.json script. 

> Note that we don't want to automatically fix errors/warnings, **npm run lint** is already configured to do the job.

**Describe alternatives you've considered**
[Lint staged](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged) seems to be a pretty good and simple solution.

**Comment by TheAkshitS** [comment]
I'm working on it. :)

**Comment by C3-TKO** [comment]
I am currently working on it - see PR #183
