### ISSUE TITLE
Consider npm audit checks / autofixes to be added to CI

### ISSUE THREAD

**Issue by C3-TKO** [Cambalab/vue-admin#184]
**Is your feature request related to a problem? Please describe.**
This project contains a lot of outdated dependencies. Some of them contain even critical security risks.

```
found 796 vulnerabilities (64 low, 3 moderate, 727 high, 2 critical) in 47508 scanned packages
  run `npm audit fix` to fix 732 of them.
  64 vulnerabilities require semver-major dependency updates.
```

**Describe the solution you'd like**
Consider adding a non failing audit stage to the CI process in Travis. At the beginning it should sufficient to just run `npm run audit` or even `npm run audit --fix` just to be aware of the outdated issues.

**Describe alternatives you've considered**
If coverage of this project is high enough you could even consider to incorporate services like https://greenkeeper.io to keep dependencies up-to-date automatically

**Comment by sgobotta** [comment]
Merged in #207
