### ISSUE TITLE
Add Image of the app running to Readme

### ISSUE THREAD

**Issue by glmaljkovich** [Cambalab/vue-admin#37]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a gif showing some of the vue-admin features. The gif could include:

+   Sign in process
+   A tour through a resource views: how a resource is created, how it's edited, etc.

It could be centered placed right after the Introduction brief in the `README.md` file.

**Describe the solution you'd like**
Any other ideas are welcome.

**Comment by sgobotta** [comment]
There you have your label ;D

**Comment by nimitbhargava** [comment]
@sgobotta Can I try this?

**Comment by sgobotta** [comment]
Sure, I'll assign it to you after updating the issue specifics.

What do you think about adding a gif showing how the login and the crud views work?

**Comment by nimitbhargava** [comment]
I will first try to run the app locally. 
`how the login and the crud views work` this would be just UI flow right?

**Comment by sgobotta** [comment]
> I will first try to run the app locally.
> `how the login and the crud views work` this would be just UI flow right?

Yeah. There are four views for each resource (a Magazines resource, for example): a create ui, a list ui, a show and an edit. It would be nice to show that flow and the login.

Feel free to upload the gif in the `/public` directory. If you have any other idea let me know.

**Comment by sgobotta** [comment]
Hello @nimitbhargava, has there been any progress?

**Comment by sgobotta** [comment]
There were no news about this, I'm unassigning @nimitbhargava from this issue so that anyone else can take it.

**Comment by sgobotta** [comment]
Merged in #186
