### ISSUE TITLE
Implement spinner/loaders on api calls for user feedback

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#5]
The best approach would be to take advantage of vuex-crud callbacks, for example:

*Full vuex-crud callbacks docs [here](https://github.com/JiriChara/vuex-crud#advanced-usage)*

```javascript
  // Callback for POST start
  onCreateStart: () => {
    // Updates the store with an 'isLoading' boolean, attribute
  },
  // Callback for POST success
  onCreateSuccess: () => {
    // Updates the store with an isLoading: false, attribute
    // Here we can also add a success dialog in the future, with an UNDO feature
  },
  // Callback for POST erro
  onCreateError: () => {
    // Updates the store with an isLoading: false, attribute
    // Here we can also add an error dialog in the future
  }
```

Vuex-crud automatically commits the START, SUCCESS or ERROR state to the store. Then the component (Create in this case) should look up the updated store state with the getter methods and render or hide a spinner depending on the isLoading boolean state.

This issue is an epic to smaller issues for the list, create and edit components.

**Comment by glmaljkovich** [comment]
Perhaps using interceptors is a simpler solution: https://github.com/JiriChara/vuex-crud#custom-client
