### ISSUE TITLE
Deprecate views components as Arrays

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#94]
At first we structured basic crud components such as Create, Edit, List, Show as arrays of **label**, **type**, **tag**, among others.
There is a route.bindings module that helps us building the routes and associates them with a given component for each crud view.
Since we refactored the resource components declaration to live as Vue components there is no need to handle the Array type views.
We need to remove the four `if ({component} instanceof Array)` statements in the **"@router/route.bindings** module. We don't need that logic anymore. Notice that when the if statement is removed, the **wrapper** variable won't be used anymore, we should remove parameters give for **list**, **show**, **create**, **edit** functions living in the route.bindings module, as well as the parameter given to them in Resource.vue, when the routes are pushed.

**Checkpoints:**

+   [x] Run the e2e tests, they should pass.
+   [x] Run the unit tests, they should pass.
+   [x] Apply your modifications
+   [x] Rerun the e2e tests, they must pass.
+   [x] Rerun the unit tests, they must pass.

**Comment by SevenIndirecto** [comment]
Hey @sgobotta I've addressed this issue in https://github.com/Cambalab/vue-admin/pull/168

**Comment by sgobotta** [comment]
Alright, I'll be taking a look, thanks!!

**Comment by sgobotta** [comment]
I assigned you to this issue, could you please mark the checkpoints in the issue template?

**Comment by sgobotta** [comment]
Merged in #168
