### ISSUE TITLE
Visual styles not being applied in the Login page

### ISSUE THREAD

**Issue by sgobotta** [Cambalab/vue-admin#95]
There is a bug where fonts and color are not being applied to the /login route

![image](https://user-images.githubusercontent.com/17838461/55282284-c96d8400-531f-11e9-849e-2138966b9a1d.png)

The issue could possibly be related to the moment Auth is instanced in the Admin.vue component. We don't want to change that at the moment. Though any updates regarding this architectural desition will be referenced here.
Proposals to this issue are accepted, discussed and then ready for implementation.

**Comment by glmaljkovich** [comment]
This is already fixed, right?

**Comment by sgobotta** [comment]
Yes and No.

Before Vuetify 2 migration it was fixed using the stylus loader vuetify used to provide. The new version of this library does not support stylues anymore, thus the styles were broken. The current solution applies css in the styles tag, which partially fixes the issue, that's mainly because the Auth is outside the Vuetify scope, ***we cannot use vuetify variables in this component***.
I think the problem is related to a misusage of the v-app directive currently applied to the `Ui` component. I guess we can fix that by using it early in the components tree, say `Admin`, for example.

**Comment by sgobotta** [comment]
Merged in #155
